<a href="https://colab.research.google.com/github/UdayKumar9381/D-3F-306/blob/main/Copy_of_FMML_2023_Basics_of_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Getting Started

FMML Module 1, Lab 1 <br>
 Module Coordinator: Amit Pandey ( amit.pandey@research.iiit.ac.in ) <br>
 Release date: Aug 2022 <br>



### In this notebook we will be covering the very basics of Python and some basic libraries such as Numpy, Matplotlib and Nltk.
#### It is suggested that you go through each line and try some examples.

#### Section 1 - Python : Basic data types and indexing.

In [ ]:
## Strings
'''
A string is a collection of one or more characters put in a single quote,
 double-quote or triple quote. In python there is no character data type,
 a character is a string of length one. It is represented by str class.

String can have special characters. String can be indexed

'''


name = 'First Lab'
name_extended = name + 'Module 1'
last_element_string = name[-1] # -1 in python is index of the last element.
## indexing is important for preprocessing of the raw data.

In [ ]:
print(name ,"\n", name_extended, "\n", last_element_string)

First Lab 
 First LabModule 1 
 b


In [ ]:
## List

'''
Lists are ordered collection of data, and are very similar to arrays,
It is very flexible as the items in a list do not need to be of the same type.
'''

name_list = ['First Lab', 3 , '1.1' , 'Lab 1'] ## notice elements are of different data type.
name_list.extend(['Module 1']) ## adding elements to list (Read about append method as well).
element_2 = name_list[1] ## Just like other languages, the index starts from 0.
two_dimesional_list = [[1,2],[3,4]] ## practice with multi-dimensional lists and arrays
## you would soon be required to handle 4 dimensional data :p :)
name_list[2] = '1.111' ##list elements can be changed

In [ ]:
print(name_list)
print(element_2)
print(two_dimesional_list)
## list can have list, dictionary, string etc.

['First Lab', 3, '1.111', 'Lab 1', 'Module 1']
3
[[1, 2], [3, 4]]


In [ ]:
## Tuples

name_tuple = ('First Lab', 1, (2,3),[1,1,'list having string']) ## A tuple can have a tuple.

print(name_tuple[2])
print("first indexing the last element of the tuple, which is a list and \n then last element of the list (a string) and then second last element of the string:")
print(name_tuple[-1][-1][-2])


(2, 3)
first indexing the last element of the tuple, which is a list and 
 then last element of the list (a string) and then second last element of the string:
n


In [ ]:
## tuples are immutable, read the error !
 #usued when passing parameters etc. and dont want them to be changed

name_tuple = (2)

In [ ]:
## Sets
'''a Set is an unordered collection of data types that is iterable, mutable and has no duplicate elements.
The order of elements in a set is undefined though it may consist of various elements.
The major advantage of using a set, as opposed to a list,
 is that it has a highly optimized method for checking whether a specific element is contained in the set.
'''
set_unique = set([1,1,2,3,5,6,'Lab1'])
print(set_unique) ##notice it is unordered
last_el = set_unique.pop()
set_unique.add((1,2))


print(last_el)
print(set_unique)

{1, 2, 3, 5, 6, 'Lab1'}
1
{2, 3, (1, 2), 5, 6, 'Lab1'}


In [ ]:
set_unique = (2) ##it is not indexable

In [ ]:
## Dictionary
'''
Dictionary in Python is an unordered collection of data values, used to store data values like a map,
 which, unlike other data types which hold only a single value as an element.
'''

dic = {'1': 'A','2':'B', 'C':3 } ##Observe how key and values can be anything
dic['4'] ='New'
print(dic)

{'1': 'A', '2': 'B', 'C': 3, '4': 'New'}


#### Question 0:
###### write down 3-5 methods applicable to each data type. (Hint: extend, reverse, etc.

In [ ]:
set1 = {1, 2,9}
set2 = {3, 4,9}
intersection_set = set1.intersection (set2)
print(intersection_set)

{9}


In [ ]:
set1 = {1, 2, 3,9}
set2= {3, 4, 5,9}
union_set = set1.union(set2)
print(union_set)

{1, 2, 3, 4, 5, 9}


In [ ]:
my_set = {1, 2, 3, 4}
my_set.remove(3)
print(my_set)

{1, 2, 4}


In [ ]:
my_set = {1, 2, 3}
my_set.add(9)
print(my_set)

{1, 2, 3, 9}


In [ ]:
my_list = []
my_list.insert(0, 1)
print(my_list)

[1]


In [ ]:
my_list = [1, 2, 3, 4, 5]
my_list.remove(3)
print(my_list)

[1, 2, 4, 5]


In [ ]:
my_list = [1, 2, 3, 4, 5]
my_list.reverse()
print(my_list)

[5, 4, 3, 2, 1]


In [ ]:
my_list = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
sub_list1= my_list [2:5]
print (sub_list1)

[3, 4, 5]


In [ ]:
my_tuple = (1, 2, 3, 4, 5)
sub_tuple= my_tuple[1:4]
print(sub_tuple)

(2, 3, 4)


In [ ]:
my_tuple = (1, 2, 3, 4, 5)
index= my_tuple.index(4)
print(my_tuple)

(1, 2, 3, 4, 5)


In [ ]:
my_tuple = (1,2,3,4)
length = len(my_tuple)
print (my_tuple)

(1, 2, 3, 4)


In [ ]:
tuple1 = (1,2)
tuple2 = (3, 4)
add_tuple= tuple1+ tuple2
print(add_tuple)

(1, 2, 3, 4)


In [ ]:
my_dict = {'name': 'uday', 'roll no.':'29'}
name = my_dict['name']
print(name)

uday


In [ ]:
my_dict = {'name': 'uday', 'roll number':'29','city':'vzm'}
del my_dict['city']
print(my_dict)

{'name': 'uday', 'roll number': '29'}


In [ ]:
my_dict = {'name': 'uday', 'roll number':'29','gender':'male'}
my_dict['gender'] = 'male'
print (my_dict)

{'name': 'uday', 'roll number': '29', 'gender': 'male'}


In [ ]:
original_dict = {'name': 'uday', 'roll no.':'29'}
new_dict = original_dict.copy()
print(new_dict)

{'name': 'uday', 'roll no.': '29'}


## Section 2 - Functions
### a group of related statements that performs a specific task.

In [ ]:
def add_new(a:str, b): ## a and b are the arguments that are passed. to provide data type hint
                              # def add_new(x: float, y: float) -> float:
  sum = a + b
  return sum

ans = add_new(1,2) ## intentionally written str, and passed int, to show it doesn't matter. It is just hint
print(ans)

3


In [ ]:
asn = add_new(1,2)

In [ ]:
def check_even_list(num_list):

    even_numbers = []

    # Go through each number
    for number in num_list:
        # Once we get a "hit" on an even number, we append the even number
        if number % 2 == 0:
            even_numbers.append(number)
        # Don't do anything if its not even
        else:
            pass
    # Notice the indentation! This ensures we run through the entire for loop
    return even_numbers

#### Question 1 :

##### Define a function, which takes in two strings A and B. Reverses the first string A, adds it to B, and returns the final string.


#### Question 2 :
##### Given a list having Names, work_hours, and gender, Write a function to print name of the female worker that worked the most hours. Also how much do should she be paid if the pay is $ 20 per hour.

##### work_hours = [('Abby',100 , 'F'),('Billy',400, 'M'),('Cassie',800,'F'), ('Maggi',600,'F'),('Alex',500,'M'),('Raj',225,'M'),('Penny',920,'F'),('Ben',300,'M')]

##### Answer : the female worker that worked the most hours is Penny and she should be paid 18400

In [ ]:
def reverse_and_concatenate(A, B):
    reversed_A = A[::-1]
    final_string = reversed_A + B
    return final_string
string_A = "yadu"
string_B = "kumar"
result = reverse_and_concatenate(string_A, string_B)
print(result)

udaykumar


In [ ]:
def find_most_hours_and_payment(work_hours):
    max_hours = 0
    female_worker_name = ""

    for name, hours, gender in work_hours:
        if gender == 'F' and hours > max_hours:
            max_hours = hours
            female_worker_name = name

    if female_worker_name:
        payment = max_hours * 20
        return f"The female worker that worked the most hours is {female_worker_name} and she should be paid ${payment}"
    else:
        return "No female workers found in the list."
work_hours = [('Abby', 100, 'F'), ('Billy', 400, 'M'), ('Cassie', 800, 'F'), ('Maggi', 600, 'F'), ('Alex', 500, 'M'), ('Raj', 225, 'M'), ('Penny', 920, 'F'), ('Ben', 300, 'M')]
result = find_most_hours_and_payment(work_hours)
print(result)

The female worker that worked the most hours is Penny and she should be paid $18400


#### Section 3 - Libraries and Reading data.

##### Numpy - One of the most used libraries - supports for large, multi-dimensional arrays and matrices, along with a large collection of high-level mathematical functions to operate on these arrays.

In [ ]:
import numpy as np

In [ ]:

a = np.array([1,1,2,3,4,5,5,6,1]) ## np.array converts given list to array

b = a>1 ## important comparison operation, where frequently used in manipulation and image processing.

print(b)
print(a[b]) ## [printing only those values in a which are greater than 1]

[False False  True  True  True  True  True  True False]
[2 3 4 5 5 6]


In [ ]:
a_range = np.arange(10,19).reshape(3,3) ## create a 3x3 array with values in range 10-19
a_range

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [ ]:
## Indexing in arrays works same as that of list

a_range[0] # printing all the columns of first row

array([10, 11, 12])

In [ ]:
a_range[:,2] #printing all the rows of second column

array([12, 15, 18])

In [ ]:
iden = np.eye(3) #idnetity matrix of given size
iden

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
## adding two matrices
summed = a_range + iden
summed


array([[11., 11., 12.],
       [13., 15., 15.],
       [16., 17., 19.]])

In [ ]:
### arrays support normal matrix multiplication that you are used to, point-wise multiplication
### and dot product as well.

mul = a_range@iden ## normal multiplication
mul


array([[10., 11., 12.],
       [13., 14., 15.],
       [16., 17., 18.]])

In [ ]:
## point wise multiplication
p_mul = a_range * iden
p_mul

array([[10.,  0.,  0.],
       [ 0., 14.,  0.],
       [ 0.,  0., 18.]])

In [ ]:
## Transpose of a matrix.

mtx_t = mul.T
mtx_t


array([[10., 13., 16.],
       [11., 14., 17.],
       [12., 15., 18.]])

In [ ]:
### Here we are changing the values of last row of the transposed matrix.
### basically point wise multiplying the values of last row with 1,2 and 3

mtx_t[2] = mtx_t[2]*[1,2,3] ## indexing, point wise multiplication and mutation of values
mtx_t

array([[10., 13., 16.],
       [11., 14., 17.],
       [12., 30., 54.]])

In [ ]:
## Just like the greater than 1 (a>1) example we saw earlier.
## here we are checking if the elements are divisible by 2 (%), and if they are, then replace by 0.

mtx_t[(mtx_t % 2 == 0)] = 0 ## convert even elements of the matrix to zero.
mtx_t

array([[ 0., 13.,  0.],
       [11.,  0., 17.],
       [ 0.,  0.,  0.]])

#### Question 3 :

##### a)Create a 5x5 matrix of the following form,

##### [[1,1]
#####  [2,2]]

#####  i.e. each row is increasing and has repetive elements.

######  Hint : you can use hstack, vstack  etc.

##### b) find dot product of the matrix with any matrix. (Figure out the size/ shape of the matrix)

In [ ]:
def find_most_hours_and_payment(work_hours):
    max_hours = 0
    female_worker_name = ""

    for name, hours, gender in work_hours:
        if gender == 'F' and hours > max_hours:
            max_hours = hours
            female_worker_name = name

    if female_worker_name:
        payment = max_hours * 20
        return f"The female worker that worked the most hours is {female_worker_name} and she should be paid ${payment}"
    else:
        return "No female workers found in the list."
work_hours = [('Abby', 100, 'F'), ('Billy', 400, 'M'), ('Cassie', 800, 'F'), ('Maggi', 600, 'F'), ('Alex', 500, 'M'), ('Raj', 225, 'M'), ('Penny', 920, 'F'), ('Ben', 300, 'M')]
result = find_most_hours_and_payment(work_hours)
print(result)

The female worker that worked the most hours is Penny and she should be paid $18400


#### Reading Files

In [ ]:
## loading from the google drive
from google.colab import drive
drive.mount('/content/gdrive')

Mounted at /content/gdrive


In [ ]:
with open ('/content/sample_data/README.md', 'r') as f:
  a = f.readlines()

a ## here a is list of elements/strings each splitted at \n, \n is also part of the list element.

['This directory includes a few sample datasets to get you started.\n',
 '\n',
 '*   `california_housing_data*.csv` is California housing data from the 1990 US\n',
 '    Census; more information is available at:\n',
 '    https://developers.google.com/machine-learning/crash-course/california-housing-data-description\n',
 '\n',
 '*   `mnist_*.csv` is a small sample of the\n',
 '    [MNIST database](https://en.wikipedia.org/wiki/MNIST_database), which is\n',
 '    described at: http://yann.lecun.com/exdb/mnist/\n',
 '\n',
 '*   `anscombe.json` contains a copy of\n',
 "    [Anscombe's quartet](https://en.wikipedia.org/wiki/Anscombe%27s_quartet); it\n",
 '    was originally described in\n',
 '\n',
 "    Anscombe, F. J. (1973). 'Graphs in Statistical Analysis'. American\n",
 '    Statistician. 27 (1): 17-21. JSTOR 2682899.\n',
 '\n',
 '    and our copy was prepared by the\n',
 '    [vega_datasets library](https://github.com/altair-viz/vega_datasets/blob/4f67bdaad10f45e3549984e17e1b3088c7315

In [ ]:
import pandas as pd

df = pd.read_csv('/content/sample_data/california_housing_test.csv','r')
df.head(10) ## pass as argument number of top elements you wish to print. Head is used to have a quick glance and understand the data.

<ipython-input-3-ad5bb400a483>:3: FutureWarning: In a future version of pandas all arguments of read_csv except for the argument 'filepath_or_buffer' will be keyword-only.
  df = pd.read_csv('/content/sample_data/california_housing_test.csv','r')


longitude,"latitude","housing_median_age","total_  ooms","total_bed  \
0  -122.050000,37.370000,27.000000,3885.000000,66...               NaN   
1  -118.300000,34.260000,43.000000,1510.000000,31...               NaN   
2  -117.810000,33.780000,27.000000,3589.000000,50...               NaN   
3  -118.360000,33.820000,28.000000,67.000000,15.0...               NaN   
4  -119.670000,36.330000,19.000000,1241.000000,24...               NaN   
5  -119.560000,36.510000,37.000000,1018.000000,21...               NaN   
6  -121.430000,38.630000,43.000000,1009.000000,22...               NaN   
7  -120.650000,35.480000,19.000000,2310.000000,47...               NaN   
8  -122.840000,38.400000,15.000000,3080.000000,61...               NaN   
9  -118.020000,34.080000,31.000000,2402.000000,63...               NaN   

   ooms","population","households","median_income","median_house_value"  
0                                                NaN                     
1                                                NaN                     
2                                                NaN                     
3                                                NaN                     
4                                                NaN                     
5                                                NaN                     
6                                                NaN                     
7                                                NaN                     
8                                                NaN                     
9                                                NaN

In [ ]:
len(df.columns), df.columns

(3,
 Index(['longitude,"latitude","housing_median_age","total_', 'ooms","total_bed',
        'ooms","population","households","median_income","median_house_value"'],
       dtype='object'))

In [ ]:
df.columns[0]

'longitude,"latitude","housing_median_age","total_'

In [ ]:
df['longitude,"latitude","housing_median_age","total_'][:5]

0    -122.050000,37.370000,27.000000,3885.000000,66...
1    -118.300000,34.260000,43.000000,1510.000000,31...
2    -117.810000,33.780000,27.000000,3589.000000,50...
3    -118.360000,33.820000,28.000000,67.000000,15.0...
4    -119.670000,36.330000,19.000000,1241.000000,24...
Name: longitude,"latitude","housing_median_age","total_, dtype: object

In [ ]:
df = df.rename(columns = {'longitude,"latitude","housing_median_age","total_':'Detail1'}) ##rename column names as at times it makes it easier for us

In [ ]:
df.head(3)

Detail1  ooms","total_bed  \
0  -122.050000,37.370000,27.000000,3885.000000,66...               NaN   
1  -118.300000,34.260000,43.000000,1510.000000,31...               NaN   
2  -117.810000,33.780000,27.000000,3589.000000,50...               NaN   

   ooms","population","households","median_income","median_house_value"  
0                                                NaN                     
1                                                NaN                     
2                                                NaN

In [ ]:
df.iloc[:5, 0]  ##iloc - index - 0 to 4 rows and first column only.

0    -122.050000,37.370000,27.000000,3885.000000,66...
1    -118.300000,34.260000,43.000000,1510.000000,31...
2    -117.810000,33.780000,27.000000,3589.000000,50...
3    -118.360000,33.820000,28.000000,67.000000,15.0...
4    -119.670000,36.330000,19.000000,1241.000000,24...
Name: Detail1, dtype: object

In [ ]:
import matplotlib
from matplotlib import pyplot as plt

In [ ]:
xpoints = np.array([1, 8])
ypoints = np.array([3, 10])

plt.plot(xpoints, ypoints)
plt.show()

NameError: ignored

In [ ]:
xpoints = np.array([1, 2, 6, 8])
ypoints = np.array([3, 8, 1, 10])

plt.plot(xpoints, ypoints)
plt.show()

## Creating a dataframe.
#### Task: Study about other methods of creating dataframe (for example: using Pandas Series, Lists etc.)

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
values = np.arange(16).reshape(4,4)
values

In [ ]:
dataframe_from_array = pd.DataFrame(values, index = ['a','b','c','d'], columns=['w','x','y','z'] )
dataframe_from_array

In [ ]:
dataframe_from_array.loc[['a','b'],['w','x']]

In [ ]:
dataframe_from_array.iloc[1,2] ## it needs position as integer

In [ ]:
dataframe_from_array.iloc[1,3] #second row and last column

In [ ]:
dataframe_from_array.iloc[::2,::2]

In [ ]:

import numpy as np
from matplotlib import pyplot as plt

ys = 200 + np.random.randn(100)
x = [x for x in range(len(ys))]

plt.plot(x, ys, '-')
plt.fill_between(x, ys, 195, where=(ys > 200), facecolor='g', alpha=0.6)

plt.title("Sample Visualization")
plt.show()

In [ ]:
## Question 3 : Upload an image to your google drive, Use plt.imread to read image from the google drive and then print that image using plt.imshow


## Answer 3 :

## 1) make sure drive is loaded and then upload a test image onto your drive

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
file_path="/content/drive/My Drive/uday.jpg"
img= plt.imread(file_path)
plt.imshow(img)